-- Grundtabeller. IF NOT EXISTS gör att skriptet är ofarligt mot en databas
-- som redan skapats av den första versionen (EnsureCreated).
CREATE TABLE IF NOT EXISTS projekt (
    "Id" uuid NOT NULL PRIMARY KEY,
    "Namn" character varying(200) NOT NULL,
    "Nummer" character varying(50) NOT NULL,
    "Kund" text NOT NULL,
    "Ansvarig" text NOT NULL,
    "Skapad" timestamp with time zone NOT NULL,
    "SkapadAv" text NOT NULL
);

CREATE TABLE IF NOT EXISTS komponent (
    "Id" uuid NOT NULL PRIMARY KEY,
    "ProjektId" uuid NOT NULL REFERENCES projekt ("Id") ON DELETE CASCADE,
    "System" text NOT NULL,
    "Beteckning" text NOT NULL,
    "Komponenttyp" text NOT NULL,
    "Signaltyp" text NOT NULL,
    "Beskrivning" text NOT NULL,
    "AnslutsTill" text NOT NULL,
    "Kabeltyp" text NOT NULL,
    "Placering" text NOT NULL,
    "Ovrigt" text NOT NULL,
    "Version" integer NOT NULL,
    "Andrad" timestamp with time zone NOT NULL,
    "AndradAv" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_komponent_ProjektId" ON komponent ("ProjektId");
CREATE INDEX IF NOT EXISTS "IX_komponent_ProjektId_Beteckning" ON komponent ("ProjektId", "Beteckning");

CREATE TABLE IF NOT EXISTS andringslogg (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjektId" uuid NOT NULL,
    "Tidpunkt" timestamp with time zone NOT NULL,
    "AnvandarId" text NOT NULL,
    "AnvandarNamn" text NOT NULL,
    "Entitet" text NOT NULL,
    "EntitetId" uuid NULL,
    "Beskrivning" text NOT NULL,
    "Falt" text NULL,
    "Fore" text NULL,
    "Efter" text NULL
);
CREATE INDEX IF NOT EXISTS "IX_andringslogg_ProjektId_Tidpunkt" ON andringslogg ("ProjektId", "Tidpunkt");
CREATE INDEX IF NOT EXISTS "IX_andringslogg_EntitetId" ON andringslogg ("EntitetId");

CREATE TABLE IF NOT EXISTS anvandarinstallning (
    "AnvandarId" text NOT NULL PRIMARY KEY,
    "Tema" text NOT NULL
);
